### PR TITLE
Comparable Proto messages

### PR DESCRIPTION
**Pull request by dmdashenkov**
In this PR we introduce the `ComparablesPlugin` and the `ComparablesJavaRenderer`, which together form the mechanism of adding the `Comparable` interface to Protobuf messages.

### CODE REVIEW

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, PTAL.

**Review by alexander-yevsyukov — CHANGES_REQUESTED** [review]
As discussed vocally, let's have separate repositories called`model-compiler`, and `model-compiler-java`, that would initially do what this PR does.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, @armiol, do we still need this PR and the repository?

**Comment by armiol** [comment]
@dmdashenkov @alexander-yevsyukov I guess, we don't need it. If there's no objections, I will delete the repository on Monday.

**Comment by alexander-yevsyukov** [comment]
@armiol, please delete.

**Pull request closed without merging**
